"use strict";
(function(){
  const $=id=>document.getElementById(id); const d=window.SCHOOL_CURRICULUM; if(!d)return;
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const today=()=>new Date().toISOString().slice(0,10);
  function currentWeek(){const t=today(); let w=d.weekMap[0]; for(const x of d.weekMap){if(t>=x.start)w=x;else break;} return w;}
  function reviewWords(listNo){const out=[];for(let i=1;i<=10;i++){const p=listNo-i;if(p>0){const a=d.spellingLists[p]||[];if(a.length)out.push(a[(i*3)%a.length]);}}return out;}
  function render(){if(!$('curriculumPanel'))return;const w=currentWeek(),list=d.spellingLists[w.spelling_list]||[],review=reviewWords(w.spelling_list);const events=[...d.schoolEvents,...d.bookDates.map(x=>[x[0],x[1],x[2]])].sort((a,b)=>a[0].localeCompare(b[0]));const upcoming=events.filter(e=>e[0]>=today()).slice(0,8);const poems=d.poems;const rotation=d.mathPlan.practice_rotation[(w.week-1)%d.mathPlan.practice_rotation.length];
    $('curriculumSummary').innerHTML='<div class="curriculum-grid"><div class="curriculum-card"><h3>📚 Grade 3 • Week '+w.week+'</h3><div class="curriculum-pill">Spelling List '+w.spelling_list+'</div><div class="curriculum-pill">30 new + 10 review</div><p class="muted">School-year plan is tied to the supplied Valley Academy calendar.</p></div><div class="curriculum-card"><h3>➕ Math Today</h3><p><b>'+esc(rotation)+'</b></p><p class="muted">The source requires 3–4 timed 100-problem practice tests each week; the operation rotation is an app supplement because the source does not prescribe an operation-by-week sequence.</p></div><div class="curriculum-card"><h3>⏰ Next Due</h3><div>'+upcoming.map(e=>'<div class="curriculum-event"><span>'+esc(e[1])+'</span><span class="curriculum-due">'+e[0]+'</span></div>').join('')+'</div></div></div>';
    $('curriculumWeek').innerHTML='<div class="curriculum-card"><h3>📝 This Week’s Spelling</h3><p class="muted">Choose only from List '+w.spelling_list+' and the 10 review words below.</p><div class="curriculum-list">'+list.map(x=>'<div class="curriculum-word">'+esc(x)+'</div>').join('')+'</div><h4>10 Review Words</h4><div class="curriculum-list">'+review.map(x=>'<div class="curriculum-word">'+esc(x)+'</div>').join('')+'</div></div>';
    $('curriculumSpelling').innerHTML='<div class="curriculum-card"><h3>🔤 Spelling Rules</h3><div class="curriculum-grid">'+d.rules.map(r=>'<div class="curriculum-card"><span class="curriculum-pill">Rule '+r[0]+'</span><b>'+esc(r[1])+'</b><p class="muted">'+esc(r[2])+'</p></div>').join('')+'</div></div>';
    $('curriculumPoems').innerHTML='<div class="curriculum-card"><h3>🎭 Poem Recitations</h3>'+poems.map(p=>'<div class="curriculum-event"><span><b>'+esc(p[2])+'</b><br><span class="muted">'+esc(p[3])+'</span></span><span class="curriculum-due">'+p[1]+'</span></div>').join('')+'</div>';
    $('curriculumMath').innerHTML='<div class="curriculum-card"><h3>➗ Math Curriculum</h3><ul>'+d.mathPlan.source_requirements.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul><h4>App Practice Rotation</h4><ul>'+d.mathPlan.practice_rotation.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></div>';
    $('curriculumBooks').innerHTML='<div class="curriculum-card"><h3>📖 Book Reports & Logs</h3>'+d.bookDates.map(x=>'<div class="curriculum-event"><span>'+esc(x[1])+'</span><span class="curriculum-due">'+x[0]+'</span></div>').join('')+'</div>';
  }
  window.CurriculumUI={render,currentWeek,reviewWords};
  document.addEventListener('DOMContentLoaded',()=>{render(); if($('curriculumTodayBtn'))$('curriculumTodayBtn').onclick=render; if($('navCurriculum'))$('navCurriculum').onclick=()=>{document.querySelectorAll('#userNav .btn').forEach(b=>b.classList.remove('active'));$('navCurriculum').className='btn primary';['parentPanel','worksheetStatusCard','progressTracker','englishPanel'].forEach(id=>$(id)?.classList.add('hidden'));$('curriculumPanel')?.classList.remove('hidden');};});
})();
